import type { PuzzleCutParams, SvgPuzzleConfig } from './types'

export function getCutParamsFromConfig(config: SvgPuzzleConfig): PuzzleCutParams {
  return {
    widthMm: config.widthMm,
    heightMm: config.heightMm,
    rows: config.rows,
    columns: config.columns,
    pieceGapMm: config.pieceGapMm,
    connectorType: config.connectorType,
    cutHeightMm: 2,
  }
}

export function buildPuzzleParamsJson(config: SvgPuzzleConfig) {
  return JSON.stringify(getCutParamsFromConfig(config), null, 2)
}

export function buildPuzzleOpenScad(params: PuzzleCutParams) {
  const rows = Math.max(1, Math.round(params.rows))
  const columns = Math.max(1, Math.round(params.columns))
  return `// Generated by foto3d.pt for a customer SVG puzzle.
// Use this STL as a negative volume over the prepared SVG/color model.

rows = ${rows};
columns = ${columns};
widthMm = ${params.widthMm};
heightMm = ${params.heightMm};
pieceGapMm = ${params.pieceGapMm};
connectorType = "${params.connectorType}";
cutHeightMm = ${params.cutHeightMm};

pieceWidthMm = widthMm / columns;
pieceHeightMm = heightMm / rows;
bladeMm = max(pieceGapMm, 0.35);
tabRadiusMm = min(pieceWidthMm, pieceHeightMm) * 0.17;
$fn = 48;

module vertical_straight_cut(x) {
  translate([x - bladeMm / 2, 0]) square([bladeMm, heightMm]);
}

module horizontal_straight_cut(y) {
  translate([0, y - bladeMm / 2]) square([widthMm, bladeMm]);
}

module vertical_round_cut(x) {
  vertical_straight_cut(x);
  for (row = [0 : rows - 1]) {
    y = row * pieceHeightMm + pieceHeightMm / 2;
    direction = ((row + floor(x / pieceWidthMm)) % 2 == 0) ? 1 : -1;
    translate([x + direction * bladeMm * 0.6, y]) circle(r = tabRadiusMm);
  }
}

module horizontal_round_cut(y) {
  horizontal_straight_cut(y);
  for (col = [0 : columns - 1]) {
    x = col * pieceWidthMm + pieceWidthMm / 2;
    direction = ((col + floor(y / pieceHeightMm)) % 2 == 0) ? 1 : -1;
    translate([x, y + direction * bladeMm * 0.6]) circle(r = tabRadiusMm);
  }
}

module vertical_chamfer_cut(x) {
  vertical_straight_cut(x);
  for (row = [0 : rows - 1]) {
    y = row * pieceHeightMm + pieceHeightMm / 2;
    direction = (row % 2 == 0) ? 1 : -1;
    translate([x, y]) polygon([
      [0, -tabRadiusMm],
      [direction * tabRadiusMm, 0],
      [0, tabRadiusMm],
      [-direction * bladeMm, 0],
    ]);
  }
}

module horizontal_chamfer_cut(y) {
  horizontal_straight_cut(y);
  for (col = [0 : columns - 1]) {
    x = col * pieceWidthMm + pieceWidthMm / 2;
    direction = (col % 2 == 0) ? 1 : -1;
    translate([x, y]) polygon([
      [-tabRadiusMm, 0],
      [0, direction * tabRadiusMm],
      [tabRadiusMm, 0],
      [0, -direction * bladeMm],
    ]);
  }
}

module vertical_cut(x) {
  if (connectorType == "redondo") {
    vertical_round_cut(x);
  } else if (connectorType == "chanfrado") {
    vertical_chamfer_cut(x);
  } else {
    vertical_straight_cut(x);
  }
}

module horizontal_cut(y) {
  if (connectorType == "redondo") {
    horizontal_round_cut(y);
  } else if (connectorType == "chanfrado") {
    horizontal_chamfer_cut(y);
  } else {
    horizontal_straight_cut(y);
  }
}

linear_extrude(height = cutHeightMm) {
  union() {
    for (col = [1 : columns - 1]) {
      vertical_cut(col * pieceWidthMm);
    }
    for (row = [1 : rows - 1]) {
      horizontal_cut(row * pieceHeightMm);
    }
  }
}
`
}
